apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: deviceshifu-siemenss7
  name: deviceshifu-siemenss7-configmap
  namespace: deviceshifu
data:
  driverProperties: |
    driverSku: siemenss7-HTTP-driver
    driverImage:
  instructions: |
    instructions:
      sendsinglebit:
      sendcontent:
      getcontent?rootaddress=Q:
      getcpuordercode:
  telemetries: |
    telemetries:
      getcontent-plc:
        properties:
          instruction: getcontent?rootaddress=Q
          pushSettings:
            telemetryCollectionService: "plc"
