apiVersion: v1
kind: Service
metadata:
  labels:
    app: deviceshifu-siemenss7
  name: deviceshifu-siemenss7-service
  namespace: deviceshifu
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: deviceshifu-siemenss7-deployment
  type: LoadBalancer
